config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :users do
    resources :lists
    resources :groups
  end

  resources :lists do
    resources :items
  end

  resources :groups do
    resources :invites
    resources :members
    resources :multi_lists
  end

  resources :items do
    resources :images
  end

  resources :profiles do
    resources :user
  end

  resources :sessions
  resources :logins
  resources :members
  resources :invites
  resources :multi_lists
  resources :items
  resources :images
  resources :products

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'
  put 'lists/:id/items/:id' => 'items#update'

  get '/admin' => 'users#index'
  get '/admin/edit' => 'users#edit'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  accepts_nested_attributes_for :items
  belongs_to :user
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    if session[:user_id]
      @lists = List.where(user_id: session[:user_id])
      @groups = Group.where(creator_id: session[:user_id])
      @user = User.find_by(id: session[:user_id])
      @invites = Invite.where(email: @user.email, name: session[:username])
      @members = Member.where(name: session[:username])
      @items = Item.where(user_id: session[:user_id])
      @multiLists = MultiList.where(user_id: session[:user_id])
    else
      redirect_to '/login'
    end
  end

  def show
    if params[:type] == "firstList"
    @list = List.find_by(user_id: params[:id].to_i)
    @lists = List.where(user_id: session[:user_id])
    @groups = Group.where(creator_id: session[:user_id])
    @multiLists = MultiList.where(user_id: session[:user_id])
    @members = Member.where(name: session[:username])
    @items = Item.where(list_id: @list.id)
    @user = User.find_by(id: session[:user_id])
    @invites = Invite.where(email: @user.email)
  else
    @list = List.find_by(id: params[:id].to_i)
    @lists = List.where(user_id: session[:user_id])
    @groups = Group.where(creator_id: session[:user_id])
    @multiLists = MultiList.where(user_id: session[:user_id])
    @members = Member.where(name: session[:username])
    @items = Item.where(list_id: @list.id)
    @user = User.find_by(id: session[:user_id])
    @invites = Invite.where(email: @user.email)
  end
  end

  def new
    @list = List.new
    @lists = List.where(user_id: session[:user_id])
    @members = Member.where(name: params[:username])
    @groups = Group.where(creator_id: session[:user_id])
    @multiLists = MultiList.where(user_id: session[:user_id])
    @user = User.find_by(id: session[:user_id])
    @invites = Invite.where(email: @user.email)
  end

  def create
    @list = List.create(list_params)
    redirect_to '/'
  end

  def destroy
    @list = List.find_by(id: params[:id])
    @items = Item.where(list_id: @list.id)
    @items.each do |item|
      item.destroy
    end
    @list.destroy
    redirect_to '/'
  end

  private
    def list_params
      params.require(:list).permit(:name, :user_id)
    end

end

app/views/lists/index.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">

                <% if @groups  && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">
      <div class="row">
        <div id="main-content" class="col-md-11 col-md-offset-1">
          <% if @invites != [] %>
          <h4>You have invites: </h4>
          <ul>
          <% @invites.each do |invite| %>
              <% group = Group.find_by(id: invite.group_id) %>
              <% if group.single_list %>
              <div id="invite" class="alert alert-warning" role="alert">
              <%= group.name %>
              <%= link_to "accept", new_group_member_path(group) %>
              <%= link_to "decline", group_invite_path(group,invite), :confirm => "Are you sure?", :method=>"delete" %>
              </div>
              <% elsif group.multi_list %>
              <div id="invite" class="alert alert-warning" role="alert">
              <%= group.name %>
              <%= link_to "accept", new_group_multi_list_path(group) %>
              <%= link_to "decline", group_invite_path(group,invite), :confirm => "Are you sure?", :method=>"delete" %>
              </div>
            <% end %>
            <% end %>
          </ul>
          <% end %>
          <h3>Master List: </h3>
          <% if @lists.empty? %>
            <div>You have no items or lists. Click <%= link_to "HERE", new_list_path, :id => "masterButton" %>to make a list</div>
          <% elsif @items.empty? %>
            <div>You have a list now but you need to add items! Click <%= link_to "HERE", list_path(session[:user_id], :type => "firstList"), :id => "masterButton" %>to add an item</div>
          <% else %>
          <% @items.each do |item| %>
            <% list = List.find_by(id: item.list_id) %>
              <div id="itemIndex" class="col-md-2">
                <div><img id="imgIndex" src="<%= item.image_url %>"></div>
                </br>
                <div><a href="<%= item.url %>"><%= item.name %></a></div>
                <div>Price: <%= number_to_currency(item.price.to_i) %></div>
                <div>quantity: <%= item.quantity %></div>
                <!-- <div class="col-md-1"><%= link_to "delete", [item.list, item], :confirm => "Are you sure you want to delete this comment?", :method => :delete %></div>
                <div class="col-md-1"><%= link_to "edit", edit_list_item_path(list.id, item, :type=> "edit") %></div> -->
              </div>
            <% end %>
          <% end %>
        </div>
        <!-- <div id="sidebar" class="col-md-2">
          <div class="well well-large">
            <h4>Lists: </h4>
            <ul class="nav nav-pills">
            <% @lists.each do |list| %>
                <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
              <% end %>
            </ul>
          </div>
          <div class="well well-large">
            <h4>Groups: </h4>
            <h6>Admin of:</h6>
            <ul class="nav nav-pills">
            <% @groups.each do |group| %>

                <li><%= link_to group.name, group_path(group.id) %></li>
              <% end %>
            </ul>
            <h6>Group member of:</h6>
            <ul class="nav nav-pills">
            <% @members.each do |member| %>
              <% group = Group.find_by(id: member.group_id) %>
              <% if group != nil %>
              <% if group.creator_id != session[:user_id] %>
                <li><%= link_to group.name, group_path(group.id) %></li>
                <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
              <% @multiLists.each do |multiList| %>
                <% group = Group.find_by(id: multiList.group_id) %>
                <% if group != nil %>
                <% if group.creator_id != session[:user_id] %>
                  <li><%= link_to group.name, group_path(group.id) %></li>
                  <%end%>
                  <%end%>
                <%end%>
              <%end%>
            </ul>

          </div>
        </div>
        </div> -->
        </div>

app/views/lists/new.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">
      <div class="row">

        <div id="main-content" class="col-md-10">
          <%= form_for @list do |f| %>
           <%= f.label :name %>
           <%= f.text_field :name %>
           </br >
           <%= f.hidden_field :user_id, :value => session[:user_id] %>
           </br >
           <%= f.submit "Add List"%>
          <% end %>
          <ul>
            <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>




        </div>
        </div>

app/views/lists/show.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">

        <div id="main-content" class="col-md-12">
          <div class="groupNav">
            <div id="addItemButton" class="groupButton width"><%= link_to "ADD ITEM", new_list_item_path(@list) %></div>
            <div id="delete" class="groupButton width"><%= link_to "DELETE LIST", list_path(@list), :method => :delete %></div>
          </div>
          <h2><%= @list.name %>:</h2>
          <div class="row">

          <% @items.each do |item| %>
            <% list = List.find_by(id: item.list_id) %>
              <div id="itemIndex" class="col-md-2">
                <div><img id="imgIndex" src="<%= item.image_url %>"></div>
                </br>
                <div><a href="<%= item.url %>"><%= item.name %></a></div>
                <div>Price: <%= number_to_currency(item.price.to_i) %></div>
                <div>quantity: <%= item.quantity %></div>
                <div><%= link_to "delete", [item.list, item], :confirm => "Are you sure you want to delete this comment?", :method => :delete %> <%= link_to "edit", edit_list_item_path(@list, item, :type=> "edit") %></div>
              </div>
            <% end %>

            </br>
            </br>
            </br>
      </div>

        <!-- <div id="sidebar" class="col-md-2">
          <div class="well well-large">
            <h4>Lists: </h4>
            <ul class="nav nav-pills">
            <% @lists.each do |list| %>
                <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
              <% end %>
            </ul>
          </div>
          <div class="well well-large">
            <h4>Groups: </h4>
            <h6>Admin of:</h6>
            <ul class="nav nav-pills">
            <% @groups.each do |group| %>

                <li><%= link_to group.name, group_path(group.id) %></li>
              <% end %>
            </ul>
            <h6>Group member of:</h6>
            <ul class="nav nav-pills">
            <% @members.each do |member| %>
              <% group = Group.find_by(id: member.group_id) %>
                <li><%= link_to group.name, group_path(group.id) %></li>

              <% end %>

            </ul>

          </div>
        </div>
        </div> -->
        </div>