config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :users do
    resources :lists
    resources :groups
  end

  resources :lists do
    resources :items
  end

  resources :groups do
    resources :invites
    resources :members
    resources :multi_lists
  end

  resources :items do
    resources :images
  end

  resources :profiles do
    resources :user
  end

  resources :sessions
  resources :logins
  resources :members
  resources :invites
  resources :multi_lists
  resources :items
  resources :images
  resources :products

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'
  put 'lists/:id/items/:id' => 'items#update'

  get '/admin' => 'users#index'
  get '/admin/edit' => 'users#edit'

end

app/models/multi_list.rb
class MultiList < ActiveRecord::Base
end

app/controllers/Multi_lists_Controller.rb
class MultiListsController < ApplicationController

def new
  @multiList = MultiList.new
  @group = Group.find_by(id: params[:group_id])
  @lists = List.where(user_id: session[:user_id])
  @MultiLists = MultiList.where(user_id: params[:user_id])
  @members = Member.where(name: params[:username])
  @groups = Group.where(creator_id: session[:user_id])
  @user = User.find_by(id: session[:user_id])
  @invites = Invite.where(email: @user.email)
end

def show
  @multiList = MultiList.find_by(id: params[:id])
  
  @group = Group.find_by(id: params[:group_id])
  @list = List.find_by(id: @multiList.list_id)
  @items = Item.where(list_id: @list.id)
  @multiLists = MultiList.where(group_id: @group.id)
  @user = User.find_by(id: @multiList.user_id)
  @lists = List.where(user_id: session[:user_id])
  @groups = Group.where(creator_id: session[:user_id])
  @members = Member.where(user_id: session[:user_id])
  @invites = Invite.where(email: @user.email)
end

def create
  @multiList = MultiList.create(multi_params)
  @user = User.find_by(id: session[:user_id])
  @invite = Invite.find_by(group_id: params[:group_id], email: @user.email)
  @invite.destroy
  redirect_to '/'
end

private
  def multi_params
    params.require(:multi_list).permit(:list_id, :group_id, :user_id)
  end



end

app/views/multi_lists/new.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">



<div id="main-container" class="container-fluid">
      <div class="row">

        <div id="main-content" class="col-md-10">
          <%= form_for [@group,@multiList] do |f| %>
           <%= f.hidden_field :user_id, :value => session[:user_id] %>
           <%= f.hidden_field :group_id, :value => params[:group_id] %>
           <%= f.label :list_id %>
           <%= f.select :list_id, options_for_seasons, :prompt => "Please select" %>
           <%= f.submit "confirm" %>
          <% end %>
          </div>

        </div>
        </div>

app/views/multi_lists/show.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">
  <div id="main-content" class="col-md-12">
    <div class="row">
    <div class="col-md-3">
      <h2><%= @group.name.upcase %>:</h2>
      <h4><%= @group.subtitle.upcase %></h4>
    </div>

      <!-- <div class="groupNav col-md-9">
        <% if @group.creator_id == session[:user_id]%>
          <div id="inviteButton" class="groupButton width"><%= link_to "INVITE", new_group_invite_path(@group.id) %></div>
        <% end %>
          <div id="addItemButton" class="groupButton width"><%= link_to "ADD ITEM", new_list_item_path(@list.id) %></div>
          <div id="sortPrice" class="groupButton width"><%= link_to "SORT BY PRICE", group_path(@group.id, :sort => "price") %></div>
          <div id="members" class="groupButton width dropdown">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUP MEMBERS</a>
            <ul class="dropdown-menu">
              <li><%= link_to "YOUR LIST", group_path(@group.id, session[:user_id]) %></li>
              <% @multiLists.each do |multiList| %>
                <% if multiList.user_id != session[:user_id] %>
                  <% user = User.find_by(id: multiList.user_id) %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% name = user.first_name + " " + user.last_name %>
              <li><%= link_to name.upcase, group_multi_list_path(group.id,multiList.id) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% if @group.creator_id == session[:user_id]%>
          <div id="delete" class="groupButton width"><%= link_to "DELETE GROUP", group_path, :method=> "delete" %></div>
        <% end %>
        <% if @group.creator_id != session[:user_id] && @group.multi_list %>
          <% multiListId = MultiList.find_by(user_id: session[:user_id]) %>
            <div id="delete" class="groupButton width"><%= link_to "LEAVE GROUP", group_member_path(@group, multiListId), :method=> "delete" %></div>
          <% end %>
        </div>
      </div>
    </div> -->

    <div class="groupNav col-md-9">
      <% if @multiList.user_id == session[:user_id]%>
        <% if @group.creator_id == session[:user_id]%>
        <div id="inviteButton" class="groupButton width"><%= link_to "INVITE", new_group_invite_path(@group.id) %></div>
        <% end %>
        <% userList = List.find_by(id: @group.list_id, user_id: session[:user_id])%>
        <% listsNow = List.where(user_id: session[:user_id]) %>
        <% listsNow.each do |list| %>
          <% if @multiList.list_id == list.id %>
        <div id="addItemButton" class="groupButton width"><%= link_to "ADD ITEM", new_list_item_path(@list.id) %></div>
          <% end %>
        <% end %>
        <div id="sortPrice" class="groupButton width"><%= link_to "SORT BY PRICE", group_path(@group.id, :sort => "price") %></div>
        <div id="members" class="groupButton width dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUP MEMBERS</a>
          <ul class="dropdown-menu">
            <li><%= link_to "YOUR LIST", group_path(@group.id, session[:user_id]) %></li>
              <% @multiLists.each do |multiList| %>
                <% if multiList.user_id != session[:user_id] %>
                  <% user = User.find_by(id: multiList.user_id) %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% name = user.first_name + " " + user.last_name %>
            <li><%= link_to name.upcase, group_multi_list_path(group.id,multiList.id) %></li>
                <% end %>
              <% end %>
          </ul>
        </div>
      <% elsif @multiList.user_id != session[:user_id] %>
        <% multi_list = MultiList.find_by(group_id: @group.id, user_id: session[:user_id])%>
        <% userList = List.find_by(id: multi_list.list_id)%>
        <% if params[:list_id] == userList.id %>
          <div id="addItemButton" class="groupButton width"><%= link_to "ADD ITEM", new_list_item_path(@list.id) %></div>
        <% end %>
          <div id="sortPrice" class="groupButton width"><%= link_to "SORT BY PRICE", group_path(@group.id, :sort => "price") %></div>
          <div id="members" class="groupButton width dropdown">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUP MEMBERS</a>
            <ul class="dropdown-menu">
              <% creatorUser = User.find_by(id: @group.creator_id) %>
              <% creatorName = creatorUser.first_name + " " + creatorUser.last_name %>
              <li><%= link_to creatorName.upcase, group_path(@group.id, @group.creator_id) %></li>
                <% @multiLists.each do |multiList| %>
                  <% if multiList.user_id != @group.creator_id && multiList.user_id != session[:user_id] %>
                    <% @userMulti = User.find_by(id: multiList.user_id) %>
                    <% group = Group.find_by(id: multiList.group_id) %>
                    <% @name = @userMulti.first_name + " " + @userMulti.last_name %>
              <li><%= link_to @name.upcase, group_multi_list_path(group.id,multiList.id) %></li>
                    <% else %>
                      <% if session[:user_id] == @group.creator_id%>
              <li><%= link_to "YOUR LIST", group_multi_list_path(@group.id, @group.list_id) %></li>
                      <% elsif multiList.user_id == session[:user_id]%>
                      <% yourList = MultiList.find_by(user_id: session[:user_id])%>
              <li><%= link_to "YOUR LIST", group_multi_list_path(@group.id, yourList) %></li>
                      <% end %>
                  <% end %>
                <% end %>
            </ul>
          </div>
        <% if @group.creator_id == session[:user_id]%>
          <div id="delete" class="groupButton width"><%= link_to "DELETE GROUP", group_path, :method=> "delete" %></div>
        <% end %>
        <% if @group.creator_id != session[:user_id] && @group.multi_list %>
          <% multiListId = MultiList.find_by(user_id: session[:user_id]) %>
          <div id="delete" class="groupButton width"><%= link_to "LEAVE GROUP", group_member_path(@group, multiListId), :method=> "delete" %></div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
    </div>


<% multiList = MultiList.find_by(id: params[:id])%>
<% @multiUserId = User.find_by(id: multiList.user_id)%>

<% if @multiUserId.id == session[:user_id] %>

<div class="row">
      <h4 class="groupListNow">Your List: </h4>
    </div>
      <div class="row">

          <div class="groupNav col-md-9">
      <% group = MultiList.find_by(id: params[:id])%>
      <% items = Item.where(list_id: group.list_id) %>
      <% items.each do |item| %>
          <div id="itemIndex" class="col-md-3">
            <div><img id="imgIndex" src="<%= item.image_url %>"></div>
            </br>
            <div><a href="<%= item.url %>"><%= item.name %></a></div>
            <div>Price: <%= number_to_currency(item.price.to_i) %></div>
            <div><%= link_to "delete", [item.list, item], :confirm => "Are you sure you want to delete this comment?", :method => :delete %></div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% if @multiUserId.id != session[:user_id] %>

<div class="row">
      <h4 class="groupListNow 1"><%= @multiUserId.first_name%> <%= @multiUserId.last_name%>'s List: </h4>
    </div>
      <% @multiListNow = MultiList.find_by(id: params[:id])%>
      <% items = Item.where(list_id: @multiList.list_id) %>
      <div class="row">
        <div class="groupNav col-md-9">

      <% items.each do |item| %>
          <div id="itemIndex" class="col-md-3">
            <div><img id="imgIndex" src="<%= item.image_url %>"></div>
            </br>
            <div><a href="<%= item.url %>"><%= item.name %></a></div>
            <div>Price: <%= number_to_currency(item.price.to_i) %></div>
            <% if item.quantity == 1 && item.quantity_bought == nil %>
              <% if item.bought == false %>
              <div><%= link_to "buy", list_item_path(@list.id, item.id, :item => {:type=> ""}), :method => :put %></div>
              <% elsif item.bought == true %>
              <% @buyer = User.find_by(id: item.bought_id) %>

              <div>Bought by: <%= @buyer.username %> <%= @buyer.last_name %></div>
                <% if session[:user_id] == item.bought_id %>
                <%= link_to "cancel", list_item_path(@list.id, item,:item => {:type=> ""}), :method => :put %>
                <% end %>
              </div>
              <% end %>
            <% else %>
              <% if item.quantity == 0 %>
                <div>
                  <%= "All Items Bought" %>
                </div>
              <% else %>
                <div>
                  <%= link_to "Buy Some or All", edit_item_path(item, :type=> "quantity") %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
<% end %>
    </div>
  </div>
</div>