config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :users do
    resources :lists
    resources :groups
  end

  resources :lists do
    resources :items
  end

  resources :groups do
    resources :invites
    resources :members
    resources :multi_lists
  end

  resources :items do
    resources :images
  end

  resources :profiles do
    resources :user
  end

  resources :sessions
  resources :logins
  resources :members
  resources :invites
  resources :multi_lists
  resources :items
  resources :images
  resources :products

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'
  put 'lists/:id/items/:id' => 'items#update'

  get '/admin' => 'users#index'
  get '/admin/edit' => 'users#edit'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :address, presence: true
  # validates :city, presence: true
  # validates :state, presence: true
  # validates :zip, presence: true
  validates :email, presence: true
  # validates :phone, presence: true
  validates_uniqueness_of :username
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
    @items = Item.where(user_id: @user.id)
    @multiLists = MultiList.where(user_id: @user.id)
    @lists = List.where(user_id: session[:user_id])
    @groups = Group.where(creator_id: session[:user_id])
    @members = Member.where(user_id: session[:user_id])
    @invites = Invite.where(email: @user.email)
  end

  def create
    if params[:user][:password] == params[:user][:password_confirmation]
    @user = User.create(user_params)
      if @user.save
        UserNotifier.send_signup_email(@user).deliver
        session[:user_id] = @user.id
        session[:username] = @user.username
        redirect_to '/'
      else
        render :new
      end
    else
      render :new
    end
  end

  def edit
    @lists = List.where(user_id: session[:user_id])
    @members = Member.where(name: params[:username])
    @groups = Group.where(creator_id: session[:user_id])
    @user = User.find_by(id: session[:user_id])
    @multiLists = MultiList.where(user_id: session[:user_id])
    @invites = Invite.where(email: @user.email)
  end

  def update
    @user = User.find_by(id: params[:id])
    @user = User.update(user_update_params)
    redirect_to '/admin'
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @lists = List.where(user_id: @user.id)
    @lists.each do |list|
      @items = Item.where(list_id: list.id)
      @items.each do |item|
        item.destroy
      end
      list.destroy
    end
    @user.destroy
    redirect_to '/admin'
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :first_name, :last_name, :address, :address2, :city, :state, :zip, :email, :phone)
    end

    def user_update_params
      params.require(:user).permit(:username, :first_name, :last_name, :address, :address2, :city, :state, :zip, :email, :phone)
    end

end

app/views/users/edit.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">


    <div id="main-container" class="container-fluid">
          <div class="row">
            <div id="main-content" class="col-md-11 col-md-offset-1">
<% if session[:user_id] == params[:id].to_i || session[:username] == "jacksrf" %>
<%= form_for @user, url: {action: 'update'} do |f| %>
 <%= f.label :username %>
 <%= f.text_field :username %>
 </br >
 <%= f.label :first_name %>
 <%= f.text_field :first_name %>
 </br >
 <%= f.label :last_name %>
 <%= f.text_field :last_name %>
 </br >
 <%= f.label :address %>
 <%= f.text_field :address %>
 </br >
 <%= f.label :address2 %>
 <%= f.text_field :address2 %>
 </br >
 <%= f.label :city %>
 <%= f.text_field :city %>
 </br >
 <%= f.label :state %>
 <%= f.text_field :state %>
 </br >
 <%= f.label :zip %>
 <%= f.text_field :zip %>
 </br >
 <%= f.label :email %>
 <%= f.email_field :email %>
 </br >
 <%= f.label :phone %>
 <%= f.telephone_field :phone %>
 </br >
 <%= f.submit "update"%>
 <% end %>

 <% else %>

 <h1>YOU DONT HAVE AUTHORIZATION FOR THIS PAGE!</h1>
 <%= link_to "go back", user_lists_path(session[:user_id]) %>
 <% end %>

 </div>
</div>
</div>

app/views/users/index.html.erb
<% if session[:username] == "jacksrf" %>
<% @users = User.all %>
<% @users.each do |user| %>
    <div class="row">
      <div class="col-md-1"><%= user.username %></div>
      <div class="col-md-1"><%= user.first_name %></div>
      <div class="col-md-1"><%= user.last_name %></div>
      <div class="col-md-2"><%= user.email %></div>
      <div class="col-md-2"><%= user.created_at %></div>
      <div class="col-md-2"><%= link_to "user profile", user_path(user) %></div>
      <div class="col-md-1"><%= link_to "delete", user_path(user), :method => :delete %></div>
    </div>
  <% end %>
  <% else %>
  <h1>You dont have access to this!</h1>
  <%= link_to "go back", user_lists_path(session[:user_id]) %>
  <% end %>

app/views/users/new.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
    </ul>
    <hr id="headerDivider">

<div id="main-container" class="container-fluid">
  <div class="row">
    <div class="signUp col-md-8 col-md-offset-2">
      <h1>WELCOME TO OneList.</h1>

      <h4>Sign up below to join!</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger" role="alert"><%= msg %></li>
        <% end %>
      </ul>
      <%= form_for @user do |f| %>
       <%= f.label :username %>
       <%= f.text_field :username %>
       </br >
       <%= f.label :password %>
       <%= f.password_field :password %>
       </br >
       <%= f.label :password_confirmation %>
       <%= f.password_field :password_confirmation %>
       </br >
       <%= f.label :first_name %>
       <%= f.text_field :first_name %>
       </br >
       <%= f.label :last_name %>
       <%= f.text_field :last_name %>
       </br >
       <!-- <%= f.label :address %>
       <%= f.text_field :address %>
       </br >
       <%= f.label :address2 %>
       <%= f.text_field :address2 %>
       </br >
       <%= f.label :city %>
       <%= f.text_field :city %>
       </br >
       <%= f.label :state %>
       <%= f.text_field :state %>
       </br >
       <%= f.label :zip %>
       <%= f.text_field :zip %>
       </br > -->
       <%= f.label :email %>
       <%= f.email_field :email %>
       </br >
       <!-- <%= f.label :phone %>
       <%= f.telephone_field :phone %>
       </br > -->
       <%= f.submit "Sign Up"%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>

          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
        <% currentUser = User.find_by(id: session[:user_id]) %>
        <% currentName = currentUser.first_name + " " + currentUser.last_name %>
        <li id="name" class="pull-right">HELLO, <%= currentName.upcase %></li>
    </ul>
    <hr id="headerDivider">


    <div id="main-container" class="container-fluid">
          <div class="row">
            <div id="main-content" class="col-md-11 col-md-offset-1">

              <% if session[:user_id] == params[:id].to_i || session[:username] == "jacksrf" %>

              <div>Your Profile Info:</div>
            </br>
              <div>Username: <%= @user.username %></div>
              <div>First name: <%= @user.first_name %></div>
              <div>Last name: <%= @user.last_name %></div>
              <div>Phone:</div>
              <div>Email:</div>
              <div>Address:</div>
            </br>
            </br>
              <%= link_to "EDIT PROFILE", edit_user_path, :class => "groupButton width" %>
              <%= link_to "CHANGE PASSWORD", new_profile_path, :class => "groupButton width" %>
              <% else %>

              <h1>YOU DONT HAVE AUTHORIZATION FOR THIS PAGE!</h1>
              <%= link_to "go back", user_lists_path(session[:user_id]) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>