config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :users do
    resources :lists
    resources :groups
  end

  resources :lists do
    resources :items
  end

  resources :groups do
    resources :invites
    resources :members
    resources :multi_lists
  end

  resources :items do
    resources :images
  end

  resources :profiles do
    resources :user
  end

  resources :sessions
  resources :logins
  resources :members
  resources :invites
  resources :multi_lists
  resources :items
  resources :images
  resources :products

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'
  put 'lists/:id/items/:id' => 'items#update'

  get '/admin' => 'users#index'
  get '/admin/edit' => 'users#edit'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
require 'nokogiri'
require 'open-uri'



  def index
    @images = []
    @item = Item.find_by(id: params[:format])
    @lists = List.where(user_id: session[:user_id])
    @groups = Group.where(creator_id: session[:user_id])
    @multiLists = MultiList.where(user_id: session[:user_id])
    @user = User.find_by(id: session[:user_id])
    @invites = Invite.where(email: @user.email, name: session[:username])
    @members = Member.where(name: session[:username])

    doc = Nokogiri::HTML(open(@item.url))
    doc.css('img').each do |link|
      if link.attributes["src"]
        image = link.attributes["src"].value
        @images.push(image)
      elsif link.attributes["data-src"]
        image = link.attributes["data-src"].value
        @images.push(image)
      end
    end
  end

  def new
    @list = List.find_by(id: params[:list_id])
    @lists = List.where(user_id: session[:user_id])
    @groups = Group.where(creator_id: session[:user_id])
    @members = Member.where(name: session[:username])
    @multiLists = MultiList.where(user_id: session[:user_id])
    @user = User.find_by(id: session[:user_id])
    @invites = Invite.where(email: @user.email)
    @item = Item.new
  end

  def create
    if params[:item][:type] == "add"
      @images = []
      @list = List.find_by(user_id: session[:user_id])
      @groups = Group.where(creator_id: session[:user_id])
      @members = Member.where(name: session[:username])
      @item = Item.create(item_params)
      redirect_to items_path(@item)
    elsif params[:item][:type] == "search"
      redirect_to products_path( :search => params[:item][:name])
    end
  end

  def edit
    @list = List.find_by(id: params[:list_id])
    @item = Item.find_by(id: params[:id])
    @group = Group.find_by(list_id: params[:list_id])
    @lists = List.where(user_id: session[:user_id])
    @groups = Group.where(creator_id: session[:user_id])
    @members = Member.where(name: session[:username])
    @user = User.find_by(id: session[:user_id])
    @invites = Invite.where(email: @user.email)
    if params[:type] == "image"
      url = params[:url]
      @item = Item.find_by(id: params[:id])
      @item.image_url = url
      @item.save
      redirect_to list_path(@item.list_id)
    end

  end

  def update
    if params[:item][:type] == "edit"
      @list = List.find_by(id: params[:list_id])
      @item = Item.find_by(id: params[:id])
      @group = Group.find_by(list_id: params[:list_id])
      @item.update(item_params)
      redirect_to list_path(@list.id)
    elsif params[:item][:type] == "quantity"
      @item = Item.find_by(id: params[:id])
      @list = List.find_by(id: @item.list_id)
      @group = Group.find_by(list_id: @list.id)
      @item.update(item_params)

      bought = @item.quantity_bought

        if bought == nil
          newQuantity_bought = params[:item][:quantity_bought]
          newQuantity = @item.quantity.to_i - params[:item][:quantity_bought].to_i
          newItem = Item.find_by(id: params[:id])
          newItem.quantity_bought = newQuantity_bought.to_i
          newItem.quantity = newQuantity.to_i
          newItem.save
          redirect_to group_path(@group)

        else
          newQuantity_bought = @item.quantity_bought.to_i + params[:item][:quantity_bought].to_i
          newQuantity = @item.quantity.to_i - params[:item][:quantity_bought].to_i
          newItem = Item.find_by(id: params[:id])
          newItem.quantity_bought = newQuantity_bought
          newItem.quantity = newQuantity
          newItem.save
          redirect_to group_path(@group)

      end
    else
      @list = List.find_by(id: params[:id])
      @item = Item.find_by(id: params[:id])
      @group = Group.find_by(list_id: params[:list_id])
      if @item.bought == false
        @item.bought = true
        @item.bought_id = session[:user_id]
        @item.save
      elsif @item.bought == true
        @item.bought = false
        @item.bought_id = nil
        @item.save
      end
    redirect_to :back
  end

  end

  def destroy
    @item = Item.find_by(id: params[:id])
    @group = Group.find_by(list_id: params[:list_id])
    @item.destroy
    redirect_to :back
  end


  private
    def item_params
      params.require(:item).permit(:name, :url, :list_id, :bought, :bought_id, :user_id, :quantity, :price)
    end

end

app/views/items/edit.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>
              <% if @invites.length == 0 %>
                <li><%= link_to "INVITES", invites_path %></li>
              <% else %>
                <% inviteTitle = "INVITES" + " ( " + @invites.length.to_s + " )"%>
                <li><%= link_to inviteTitle, invites_path %></li>
                <% end %>
          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">
      <div class="row">
        <div id="main-content" class="col-md-9">

      <% if params[:type] == "quantity" %>
        <%= form_for [@list,@item]  do |f| %>
          <%= f.hidden_field :name, :value => @item.name %>
          <%= f.hidden_field :url, :value => @item.url %>
          <%= f.hidden_field :price, :value => @item.price %>
          <%= f.hidden_field :bought, :value => @item.bought %>
          <%= f.hidden_field :list_id, :value => @item.list_id %>
          <%= f.hidden_field :bought_id, :value => @item.bought_id %>
          <%= f.hidden_field :type, :value => "quantity" %>
          <%= f.hidden_field :quantity, :value => 0 %>
          <%= f.label :quantity %>
          <%= f.text_field :quantity_bought %>
        <%= f.submit "confirm" %>
        <% end %>
        <% else %>
        <%= form_for [@list,@item] do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, :value => @item.name %>
          </br >
          <%= f.label :url %>
           <%= f.text_field :url, :value => @item.url %>
           </br >
           <%= f.label :price %>
           <%= f.text_field :price, :value => @item.price %>
           </br >
           <%= f.label :quantity %>
           <%= f.text_field :quantity, :value => @item.quantity %>
           </br >
           <%= f.hidden_field :list_id, :value => @item.list_id %>
           <%= f.hidden_field :bought, :value => "true" %>
           <%= f.hidden_field :bought_id, :value => session[:user_id] %>
           <%= f.hidden_field :type, :value => "edit" %>
          <%= f.submit "confirm" %>
          <% end %>
          <% end %>
</div>

</div>
</div>

app/views/items/index.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>
              <% if @invites.length == 0 %>
                <li><%= link_to "INVITES", invites_path %></li>
              <% else %>
                <% inviteTitle = "INVITES" + " ( " + @invites.length.to_s + " )"%>
                <li><%= link_to inviteTitle, invites_path %></li>
                <% end %>
          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">
      <div class="row">
        <div id="main-content" class="col-md-9 col-md-offset-1">
          <h4>Pick an Image for your item: </h4>
          <div class="col-md-10">

            <% if @images.length == 0 %>
              <div>No images found on search, click continue!</div>

              <div><%= link_to "Continue", edit_item_path(params[:format], :type=> "image") %></div>
            <% else %>
          <% @images.each do |image| %>
              <div id="imageIndex" class="col-md-2"><img id="imgSearch" class="img-rounded" src="<%= image %>"> <%= link_to "Use this Image", edit_item_path(params[:format], :url => image, :type=> "image") %></div>
            <% end %>
            <% end %>

        </div>
      </div>

        <div id="sidebar" class="col-md-2">

          <div class="well well-large">
            <h4>Lists: </h4>
            <ul class="nav nav-pills">
            <% @lists.each do |list| %>
                <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
              <% end %>
            </ul>
          </div>
          <div class="well well-large">
            <h4>Groups: </h4>
            <h6>Admin of:</h6>
            <ul class="nav nav-pills">
            <% @groups.each do |group| %>

                <li><%= link_to group.name, group_path(group.id) %></li>
              <% end %>
            </ul>
            <h6>Group member of:</h6>
            <ul class="nav nav-pills">
            <% @members.each do |member| %>
              <% group = Group.find_by(id: member.group_id) %>
              <% if group != nil %>
              <% if group.creator_id != session[:user_id] %>
                <li><%= link_to group.name, group_path(group.id) %></li>
                <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
              <% @multiLists.each do |multiList| %>
                <% group = Group.find_by(id: multiList.group_id) %>
                <% if group != nil %>
                <% if group.creator_id != session[:user_id] %>
                  <li><%= link_to group.name, group_path(group.id) %></li>
                  <%end%>
                  <%end%>
                <%end%>
              <%end%>
            </ul>

          </div>

        </div>

        </div>
        </div>

app/views/items/new.html.erb
<div class="bs-example">
    <ul id="navHeader" class="nav nav-pills">
        <li>
          <div id="logo"><a href="http://www.onelist.io">OneList.</a></div>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">ACTIONS <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "ADD A LIST", new_list_path %></li>
                <li><%= link_to "ADD A GROUP", new_group_path %></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">LISTS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @lists.empty? %>
                  <li>No lists Yet</li>
                <% else %>
                <% @lists.each do |list| %>
                    <li><%= link_to list.name, user_list_path(list.user_id, list.id)%></li>
                  <% end %>
                  <% end %>
              </ul>

          <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">GROUPS <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if @groups.empty? && @members.empty? && @multiLists.empty? %>
                  <li>No Groups Yet</li>
                <% else %>
                <% @groups.each do |group| %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% @members.each do |member| %>
                  <% group = Group.find_by(id: member.group_id) %>
                  <% if group != nil %>
                  <% if group.creator_id != session[:user_id] %>
                    <li><%= link_to group.name, group_path(group.id) %></li>
                  <% end %>
                <% end %>
              <% end %>
              <% if @multiLists %>
                <% @multiLists.each do |multiList| %>
                  <% group = Group.find_by(id: multiList.group_id) %>
                  <% if group != nil %>
                    <% if group.creator_id != session[:user_id] %>
                      <li><%= link_to group.name, group_path(group.id) %></li>
                    <%end%>
                  <%end%>
                <%end%>
              <%end%>
              <%end%>
              </ul>
              <% if @invites.length == 0 %>
                <li><%= link_to "INVITES", invites_path %></li>
              <% else %>
                <% inviteTitle = "INVITES" + " ( " + @invites.length.to_s + " )"%>
                <li><%= link_to inviteTitle, invites_path %></li>
                <% end %>
          <li class="pull-right"><form method="POST" action="/session">
            <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
            <input name="_method" value="DELETE" type="hidden">
            <button>LOGOUT</button>
          </form></li>
        <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">SETTINGS<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "PROFILE", user_path(session[:user_id]) %></li>
                <% if session[:username] == "jacksrf" %>
                <li><%= link_to "ADMIN", users_path %></li>
                <% end %>
            </ul>
        </li>
    </ul>
    <hr id="headerDivider">


<div id="main-container" class="container-fluid">
      <div class="row">
        <div id="main-content" class="col-md-10">
<h1> Add item to <%= @list.name %>: </h1>

<%= form_for [@list,@item] do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 </br >
 <%= f.label :url %>
 <%= f.text_field :url %>
  </br >
  <%= f.label :price %>
  <%= f.number_field :price %>
  </br >
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  </br >
 <%= f.hidden_field :list_id, :value => @list.id %>
 <%= f.hidden_field :bought, :value => false %>
 <%= f.hidden_field :user_id, :value => session[:user_id] %>
 </br >
 <%= f.submit "Add Item"%>
<% end %>
</div>


</div>
</div>